# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=7)),
                ('peso', models.IntegerField()),
            ],
        ),
    ]
